import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TINYUH",
<<<<<<< HEAD
  <link rel="icon"
  href="tiny-icon.ico" />
  description: "Generated by create next app",
};link 
=======
  description: "Tinyuh",
};
>>>>>>> 54565e1833b7a8f37d254647b5a0344b991a5ab7

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="bg-black min-h-screen font-helvetica">{children}</section>
      </body>
    </html>
  );
}
